services:
  neo4j-budget:
    image: neo4j:5
    container_name: neo4j-budget
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/passw0rd
    volumes:
      - ./neo4j-import:/import
      - neo4j-data:/data

  redis-budget:
    image: redis:7-alpine
    container_name: redis-budget
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog-budget
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    networks:
      - app-network

volumes:
  neo4j-data:
  redis-data:

networks:
  app-network:
    driver: bridge